[project]
authors = ["Alexey"]
entry = "main.sw"
license = "Apache-2.0"
name = "functions_test_script"

[dependencies]
sway_libs = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.4.1" }
oracle_abi = { path = "../../abi/oracle_abi" }
