name: Deploy

env:

on:
  push:
    branches:
      - master
      - develop

jobs:
  deploy_to_Heroku:
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_EMAIL: lidia.zhabo99@gmail.com
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DEVELOP
        if: endsWith(github.ref, '/develop')
        run: |
          echo "HEROKU_APP_NAME=sway-lend-stage" >> $GITHUB_ENV
      - name: Deploy to PROD
        if: endsWith(github.ref, '/master')
        run: |
          echo "HEROKU_APP_NAME=sway-lend" >> $GITHUB_ENV
      - name: Run chekout
        uses: actions/checkout@v2
      - name: Set env
        run: heroku config:set REACT_APP_API_BASE=${{env.REACT_APP_API_BASE}} -a ${{ env.HEROKU_APP_NAME }}
      - name: Deploy to ${{ env.HEROKU_APP_NAME }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ env.HEROKU_APP_NAME }}
          heroku_email: "lidia.zhabo99@gmail.com"
          buildpack: "https://buildpack-registry.s3.amazonaws.com/buildpacks/mars/create-react-app.tgz"
